import {
  faBootstrap,
  faCss3Alt,
  faGithub,
  faGitlab,
  faHtml5,
  faReact,
  faSass,
  faSquareJs,
  faAngular,
  faPhp,
  faLaravel,
  faFigma,
  faNode,
} from "@fortawesome/free-brands-svg-icons";
import {
  faDatabase,
  faServer,
  faPalette,
  faBolt,
  faCodeBranch,
  faCloud,
} from "@fortawesome/free-solid-svg-icons";
import { images } from "./index";

const skillCategories = [
  {
    title: "Frontend Development",
    skills: [
      { name: "JavaScript", icon: faSquareJs },
      { name: "TypeScript", icon: faSquareJs },
      { name: "React.js", icon: faReact },
      { name: "React Native", icon: faReact },
      { name: "Next.js", icon: faServer },
      { name: "Angular", icon: faAngular },
      { name: "HTML5", icon: faHtml5 },
      { name: "CSS3", icon: faCss3Alt },
    ],
  },
  {
    title: "State Management",
    skills: [
      { name: "Redux", icon: faBolt },
      { name: "Zustand", icon: faBolt },
      { name: "useContext", icon: faReact },
      { name: "RTK Query", icon: faBolt },
    ],
  },
  {
    title: "Styling & UI",
    skills: [
      { name: "Tailwind CSS", icon: faPalette },
      { name: "Ant Design", icon: faPalette },
      { name: "MUI", icon: faPalette },
      { name: "ShadCN", icon: faPalette },
      { name: "SASS", icon: faSass },
      { name: "Bootstrap", icon: faBootstrap },
      { name: "Framer Motion", icon: faBolt },
    ],
  },
  {
    title: "APIs & Integrations",
    skills: [
      { name: "RESTful APIs", icon: faServer },
      { name: "Axios", icon: faServer },
      { name: "RTK Query", icon: faBolt },
    ],
  },
  {
    title: "Version Control",
    skills: [
      { name: "Git", icon: faCodeBranch },
      { name: "GitHub", icon: faGithub },
      { name: "GitLab", icon: faGitlab },
      { name: "Azure", icon: faCloud },
    ],
  },
  {
    title: "Design Tools",
    skills: [
      { name: "Figma", icon: faFigma },
      { name: "Photoshop", icon: faPalette },
      { name: "CorelDraw", icon: faPalette },
      { name: "Canva", icon: faPalette },
    ],
  },
  {
    title: "Backend & Extra",
    skills: [
      { name: "Node.js", icon: faNode },
      { name: "PHP", icon: faPhp },
      { name: "Laravel", icon: faLaravel },
      { name: "MySQL", icon: faDatabase },
      { name: "MongoDB", icon: faDatabase },
      { name: "Firebase", icon: faServer },
      { name: "Express", icon: faServer },
    ],
  },
];

const experiences = [
  {
    title: "Frontend Developer",
    company: "AlasilaCX",
    date: "March 2025 - Present",
    location: "Cairo, Egypt",
    type: "Full-time | On site",
    points: [
      "Leading frontend development for Edafi, an on-demand workforce platform similar to Instawork.",
      "Developing and maintaining two React Native mobile applications: Edafi Business & Edafi Seekers.",
      "Building and maintaining the Edafi web application.",
      "Playing a key role in developing the CRM web application, improving client management and internal workflow automation.",
      "Applied micro frontend principles to modularize features, enabling independent development and deployment.",
    ],
  },
  {
    title: "Frontend Developer",
    company: "CodeyAI",
    date: "Sep 2024 - March 2025",
    location: "New York, USA",
    type: "Part-time | Remote",
    points: [
      "Developed CodeyAI, an AI-powered platform converting intelligent diagrams into fully functional project code.",
      "Designed intuitive UIs for creating and managing diagram-based programming workflows.",
      "Integrated AI features including diagrammatic architecture design, automated code generation, and GPT-style chat.",
      "Enhanced usability, improving user productivity by 30% through seamless project metadata.",
    ],
    link: "https://www.codeyai.com",
  },
  {
    title: "Frontend Developer",
    company: "Quadratix",
    date: "Dec 2022 - Jan 2025",
    location: "Cairo, Egypt",
    type: "Full-time | Hybrid",
    points: [
      "Contributed to a situation awareness application for a military training center.",
      "Designed user-friendly interfaces for real-time data updates ensuring accurate information delivery.",
      "Collaborated with cross-functional teams to integrate frontend with complex hardware and communication systems.",
      "Maintained focus on performance, usability, and security under strict confidentiality requirements.",
    ],
  },
  {
    title: "Frontend Developer",
    company: "Prosoft",
    date: "Oct 2021 - Oct 2022",
    location: "Saudi Arabia",
    type: "Full-time | Remote",
    points: [
      "Led the UI team in designing interfaces for e-commerce, ERP, and informational applications.",
      "Integrated APIs with frontend components for seamless UI-backend interaction.",
      "Collaborated with backend teams to ensure efficient data flow across multiple projects.",
      "Mentored junior team members and conducted code reviews to uphold development standards.",
    ],
  },
  {
    title: "Frontend Developer",
    company: "Sintac Code",
    date: "July 2021 - Jan 2022",
    location: "Giza, Egypt",
    type: "Part-time | Hybrid",
    points: [
      "Developed and maintained web applications, ensuring scalability and responsiveness.",
      "Designed full-stack solutions, integrating frontend interfaces with backend systems.",
      "Led code optimization efforts, boosting application performance and user experience.",
    ],
  },
];

const education = [
  {
    title: "Bachelor's Degree of Science",
    institution: "Cairo University (CU)",
    year: "2021",
    grade: "Good",
  },
  {
    title: "Fullstack Development",
    institution: "Information Technology Institute (ITI)",
    year: "",
    grade: "",
  },
  {
    title: "Software Engineering",
    institution: "ALX - Africa Program",
    year: "",
    grade: "",
  },
];

const projects = [
  {
    name: "CodeyAi",
    img: images.codeyai,
    github: null,
    website: "https://codeyai.com/",
    featured: true,
    category: "production",
    tech: ["React.js", "TypeScript", "AI"],
  },
  {
    name: "Organica-Group",
    img: images.organica,
    github: null,
    website: "https://organica-group.com/",
    featured: true,
    category: "production",
    tech: ["React.js", "Next.js"],
  },
  {
    name: "Modern-North",
    img: images.modernNorth,
    github: null,
    website: "https://modern-north-sa.com/",
    featured: true,
    category: "production",
    tech: ["React.js", "Next.js"],
  },
  {
    name: "CrEpTo",
    img: images.project13,
    github: "https://github.com/khaledmasry0/CrEpTo",
    website: "https://khaledmasry0.github.io/CrEpTo/",
    category: "personal",
    tech: ["React.js", "API"],
  },
  {
    name: "GPT-3",
    img: images.project9,
    github: "https://github.com/khaledmasry0/GPT-3-Site",
    website: "https://khaledmasry0.github.io/GPT-3-Site/",
    category: "personal",
    tech: ["React.js"],
  },
  {
    name: "Elmasry-Commerce",
    img: images.project2,
    github: "https://github.com/khaledmasry0/Elmasry-e-Shop",
    website: "https://am-commerce.web.app/",
    category: "personal",
    tech: ["React.js", "Firebase"],
  },
  {
    name: "eShop",
    img: images.project4,
    github: "https://github.com/khaledmasry0/eShop",
    website: "https://khaledmasry0.github.io/eShop/",
    category: "personal",
    tech: ["React.js"],
  },
  {
    name: "VawulensGym",
    img: images.project3,
    github: "https://github.com/khaledmasry0/VawulensGym",
    website: "http://vawulensgym-app.surge.sh/",
    category: "personal",
    tech: ["React.js"],
  },
  {
    name: "YoutubeClone",
    img: images.project6,
    github: "https://github.com/khaledmasry0/YouTube-Clone",
    website: "https://khaledmasry0.github.io/YouTube-Clone/",
    category: "personal",
    tech: ["React.js", "API"],
  },
  {
    name: "SocialX",
    img: images.project7,
    github: "https://github.com/khaledmasry0/SocialX",
    website: "https://khaledmasry0.github.io/SocialX/",
    category: "personal",
    tech: ["React.js"],
  },
  {
    name: "Delivery",
    img: images.project5,
    github: "https://github.com/khaledmasry0/Delivery-Website",
    website: "https://khaledmasry0.github.io/Delivery-Website/",
    category: "personal",
    tech: ["HTML", "CSS", "JS"],
  },
  {
    name: "DesineyClone",
    img: images.project8,
    github: "https://github.com/khaledmasry0/DisenyClone",
    website: "https://disenyclone-62e0f.web.app/",
    category: "personal",
    tech: ["React.js", "Firebase"],
  },
  {
    name: "Movies Search",
    img: images.project1,
    github: "https://github.com/khaledmasry0/Movies-WebSite",
    website: "https://khaledmasry0.github.io/Movies-WebSite/",
    category: "personal",
    tech: ["React.js", "API"],
  },
  {
    name: "Tic-Tac-Toe",
    img: images.xo,
    github: "https://github.com/khaledmasry0/Tec-Tac-Toe-Game/",
    website: "https://khaledmasry0.github.io/Tec-Tac-Toe-Game/",
    category: "personal",
    tech: ["JavaScript"],
  },
  {
    name: "Products Management",
    img: images.project12,
    github: "https://github.com/khaledmasry0/ManagementSystem",
    website: "https://khaledmasry0.github.io/ManagementSystem/",
    category: "personal",
    tech: ["JavaScript"],
  },
  {
    name: "Weather App",
    img: images.project11,
    github: "https://github.com/khaledmasry0/weatherApp",
    website: "https://khaledmasry0.github.io/weatherApp/",
    category: "personal",
    tech: ["JavaScript", "API"],
  },
  {
    name: "Password Generator",
    img: images.project10,
    github: "https://github.com/khaledmasry0/PW-generatot",
    website: "https://khaledmasry0.github.io/PW-generatot/",
    category: "personal",
    tech: ["JavaScript"],
  },
];

const personalInfo = {
  name: "Khaled Mohamed",
  title: "Senior Front-end Developer",
  phone: "+201011131316",
  email: "khaledmohamed3360@gmail.com",
  location: "Faisal-Giza, Egypt",
  linkedin: "https://www.linkedin.com/in/khaled-elmasry-4b4689255/",
  github: "https://github.com/khaledmasry0",
  birthdate: "1997-05-12",
  bio: "A Senior Frontend Developer with over 5 years of experience building fast, scalable, and user-centered web applications. Skilled in React.js, React Native, TypeScript, and performance optimization, with a solid understanding of frontend architecture and micro frontend principles. I enjoy turning complex ideas into clean, intuitive interfaces and delivering products that combine performance, usability, and security.",
  languages: [
    { name: "Arabic", level: "Native" },
    { name: "English", level: "Conversational" },
  ],
};

const dataExport = { skillCategories, experiences, education, projects, personalInfo };
export default dataExport;
